[package]
name = "aflak_imgui-glium-renderer"
version = "0.19.1"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "Glium renderer for the imgui crate"
homepage = "https://github.com/malikolivier/imgui-rs"
repository = "https://github.com/malikolivier/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "rendering"]

[dependencies]
glium = { version = "0.22", default-features = false }
aflak_imgui = { version = "0.19.1", path = "../" }
aflak_imgui-sys = { version = "0.19.1", path = "../imgui-sys", features = ["glium"] }
