[package]
name = "aflak_imgui-sys"
version = "0.18.1"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "Raw FFI bindings to dear imgui"
homepage = "https://github.com/malikolivier/imgui-rs"
repository = "https://github.com/malikolivier/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "external-ffi-bindings"]
build = "build.rs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
glium = { version = "0.20", default-features = false, optional = true }
gfx = { version = "0.17", optional = true }

[build-dependencies]
cc = "1.0"
